### ISSUE TITLE
No leader after reconnecting a follower twice

### ISSUE THREAD

**Issue by halohalospecial** [skirino/rafted_value#3]
Hi!  I don't know if this is the expected behavior, but the cluster doesn't have a leader anymore after reconnecting a follower twice.

```
# Node 1
$ iex --sname server1 -S mix

# Node 2
$ iex --sname server2 -S mix

# Node 3
$ iex --sname server3 -S mix

Node.connect(:"server1@host")
Node.connect(:"server2@host")
```

```
# Node 1
rv_config = RaftedValue.make_config(QueueWithLength)
RaftedValue.start_link({:create_new_consensus_group, rv_config}, name: :server1)

# Node 2
RaftedValue.start_link({:join_existing_consensus_group, [{:server1, :"server1@host"}]}, name: :server2)

# Node 3
RaftedValue.start_link({:join_existing_consensus_group, [{:server1, :"server1@host"}]}, name: :server3)
```

```
# Node 1
RaftedValue.query(:server1, :length)

# {:ok, 0}
```

```
# Stop Node 2

# Reconnect Node 2
$ iex --sname server2 -S mix

Node.connect(:"server1@host")
RaftedValue.start_link({:join_existing_consensus_group, [{:server1, :"server1@host"}]}, name: :server2)
```

```
# Node 1
RaftedValue.query(:server1, :length)

# {:ok, 0}
# Still works
```

```
# Stop Node 2

# Reconnect Node 2 again
$ iex --sname server2 -S mix

Node.connect(:"server1@host")
RaftedValue.start_link({:join_existing_consensus_group, [{:server1, :"server1@host"}]}, name: :server2)

# ** (EXIT from #PID<0.159.0>) shell process exited with reason: an exception was raised:
    ** (RaftedValue.AddFollowerError) no leader found
        (rafted_value) lib/rafted_value/server.ex:238: RaftedValue.Server.call_add_server/1
        (rafted_value) lib/rafted_value/server.ex:228: RaftedValue.Server.call_add_server_and_reraise_with_pid/1
        (rafted_value) lib/rafted_value/server.ex:217: RaftedValue.Server.call_add_server_with_fault_injection/2
        (rafted_value) lib/rafted_value/server.ex:194: RaftedValue.Server.initialize_follower_state/2
        (rafted_value) lib/rafted_value/server.ex:112: RaftedValue.Server.init/1
        (stdlib) gen_statem.erl:676: :gen_statem.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

```
# Node 1
RaftedValue.query(:server1, :length)

# {:error, {:not_leader, nil}}
```

**Comment by skirino** [comment]
It's expected.
When you stop "Node 2" second time, 2 out of 4 processes are dead:
1. process in Node 1: alive
2. process in original Node 2: dead
3. process in Node 3: alive
4. process in restarted Node 2: dead

You might want automatic cleanup of processes in dead nodes.
Detection of unreachable nodes and automated cleanup are implemented in [raft_fleet](https://github.com/skirino/raft_fleet).

**Comment by halohalospecial** [comment]
Thanks for the quick response :+1:
